### PR TITLE
Improve readme and convert to markdown

### PR DESCRIPTION
**Pull request by zerfgog**
This PR improves readability of the readme as well as updating some outdated language and usage instructions. This also allows the readme to be displayed at the front page of the repository, which can be previewed in my fork.

Note that I've listed the changelog-in-a-readme system as deprecated and have advised readers to use the GitHub commit list. The existing changelog is kept in for historical reasons, but can be removed if you want.

### CODE REVIEW

**Comment by Nayruden** [comment]
@zerfgog, first I want to say thank you. You obviously spent some time on this. I've been meaning to update the readme for some time.

However, it's formatted the way it is for our documentation generator -- http://ulyssesmod.net/docs/files/ULib_readme-txt.html. That being said, there's no real reason why we couldn't exclude the readme from the documentation. Doing so has always felt clunky to me, but more people probably view the readme here than from the online documentation. I'll consult with the rest of the team on this.

However, we definitely do still maintain a changelog and make regular releases -- I know our recent history has not been great for releases, but we intend to release more often.

**Comment by zerfgog** [comment]
If you still plan on keeping a recorded text changelog, what do you think about moving it to a separate file to reduce readme length?

**Comment by Nayruden** [comment]
That's a fair idea.

**Comment by zerfgog** [comment]
#19

**Pull request closed without merging**
