### PR TITLE
Fix formatting issues in 'ulx debuginfo'

### LINKED ISSUE #81: ULX debuginfo formatting issues
Two issues:

SteamIDs are now one character longer, need to adjust spacing

Unicode characters count as two characters, even though they only take one space and thus throw off the formatting.

### PR DESCRIPTION
**Pull request by Toxsa**
Fixes #81.

Proposed changes:
- Adjust spacing to accommodate longer SteamIDs
- Take multibyte Unicode characters into account when calculating spacing

Noticed the issue has been open for a little while. Wanted to see if I could help with the patch. What do you think about this approach?

### CODE REVIEW

**Comment by Toxsa** [comment]
Whoops! I didn't want to submit this yet, but I accidentally pressed enter. I will re-open once I verified all my changes.

**Comment by Nayruden** [comment]
Seems like that will work perfectly! Why did you use utf8.force? Have you
observed invalid characters in the wild?

**Comment by yupi2** [comment]
@Nayruden I think there's a thing where a Steam name can have a truncated UTF-8 codepoint in last byte or two of the name. Not positive about it though

**Comment by Toxsa** [comment]
I used utf8.force because:
- It's relatively easy to craft an addon.txt file that has an invalid byte sequence in its name.
- Addons may override player:Nick. Some rely on user input. I don't trust them to always return valid UTF-8.
- On most Unix systems, file names can be arbitrary binary data with very few limitations.

Depending on how much you trust Steam, it may be excessive to sanitize the names of workshop addons.

**Pull request merged**
